# -*- coding: utf-8 -*-
"""OIBSIP_TASKNO2 BMI CALC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYW86cnOd5N8Phz2YlPvFcHU-Zb2uJzi
"""

Height = float(input("Enter the height in cm: "))
Weight = float(input("Enter the weight in kg: "))
#a function for BMI
BMI = Weight / (Height/100)**2
print("Your Body Mass Index is", BMI)
if BMI <= 18.5:
    print("Oops! You are underweight.")
elif BMI <= 24.9:
    print("Awesome! You are healthy.")
elif BMI <= 29.9:
    print("Eee! You are over weight.")
else:
    print("Seesh! You are obese.")
